name: TDR Tag and pre deploy
on:
  push:
    branches:
      - main
permissions: {}
jobs:
  pre-deploy-keycloak-user:
    permissions:
      id-token: write
      contents: write
    uses: nationalarchives/tdr-github-actions/.github/workflows/lambda_build.yml@f318ce8a5d99c08b1235663f97fdb1b35844674e # v0.0.39
    with:
      lambda-name: create-keycloak-user
      repo-name: tdr-create-db-users
      artifact-name: create-db-users
      build-command: |
        sbt assembly
    secrets:
      MANAGEMENT_ACCOUNT: ${{ secrets.MANAGEMENT_ACCOUNT }}
      WORKFLOW_PAT: ${{ secrets.WORKFLOW_PAT }}
  pre-deploy-db-users:
    needs: pre-deploy-keycloak-user
    permissions:
      id-token: write
      contents: write
    uses: nationalarchives/tdr-github-actions/.github/workflows/lambda_build.yml@f318ce8a5d99c08b1235663f97fdb1b35844674e # v0.0.39
    with:
      lambda-name: create-db-users
      repo-name: tdr-create-db-users
      artifact-name: create-db-users
      build-command: |
        sbt assembly
    secrets:
      MANAGEMENT_ACCOUNT: ${{ secrets.MANAGEMENT_ACCOUNT }}
      WORKFLOW_PAT: ${{ secrets.WORKFLOW_PAT }}
  deploy:
    needs: [pre-deploy-keycloak-user, pre-deploy-db-users]
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - run: gh workflow run deploy.yml -f environment=intg -f keycloak-to-deploy="$KEYCLOAK_VERSION" -f db-to-deploy="$DB_VERSION"
        env:
          KEYCLOAK_VERSION: ${{ needs.pre-deploy-keycloak-user.outputs.next-version }}
          DB_VERSION: ${{ needs.pre-deploy-db-users.outputs.next-version }}
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_PAT }}
